#include "ip2region.h"
/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void Go2cppFn_ConvertDbToTxt(char* in, int inLen, char** out, int* outLen);
extern __declspec(dllexport) void Go2cppFn_ConvertTxtToDb(char* in, int inLen, char** out, int* outLen);
extern __declspec(dllexport) void Go2cppFn_TxtToXdb(char* in, int inLen, char** out, int* outLen);

#ifdef __cplusplus
}
#endif


std::string ConvertDbToTxt(ConvertDbToTxt_Req in0){
	std::string in;
	{
		{
			uint32_t tmp9 = in0.DbFileName.length();
			char tmp10[4];
			tmp10[0] = (uint32_t(tmp9) >> 24) & 0xFF;
			tmp10[1] = (uint32_t(tmp9) >> 16) & 0xFF;
			tmp10[2] = (uint32_t(tmp9) >> 8) & 0xFF;
			tmp10[3] = (uint32_t(tmp9) >> 0) & 0xFF;
			in.append(tmp10, 4);
			in.append(in0.DbFileName);
		}
		{
			uint32_t tmp11 = in0.TxtFileName.length();
			char tmp12[4];
			tmp12[0] = (uint32_t(tmp11) >> 24) & 0xFF;
			tmp12[1] = (uint32_t(tmp11) >> 16) & 0xFF;
			tmp12[2] = (uint32_t(tmp11) >> 8) & 0xFF;
			tmp12[3] = (uint32_t(tmp11) >> 0) & 0xFF;
			in.append(tmp12, 4);
			in.append(in0.TxtFileName);
		}
		in.append((char*)(&in0.Merge), 1);
	}
	char *out = NULL;
	int outLen = 0;
	Go2cppFn_ConvertDbToTxt((char *)in.data(), in.length(), &out, &outLen);
	std::string retValue;
	int outIdx = 0;
	{
		uint32_t tmp13 = 0;
		uint32_t tmp14 = uint32_t(uint8_t(out[outIdx+0]) << 24);
		uint32_t tmp15 = uint32_t(uint8_t(out[outIdx+1]) << 16);
		uint32_t tmp16 = uint32_t(uint8_t(out[outIdx+2]) << 8);
		uint32_t tmp17 = uint32_t(uint8_t(out[outIdx+3]) << 0);
		tmp13 = tmp14 | tmp15 | tmp16 | tmp17;
		outIdx+=4;
		retValue = std::string(out+outIdx, out+outIdx+tmp13);
		outIdx+=tmp13;
	}
	if (out != NULL) {
		free(out);
	}
	return retValue;
}

std::string ConvertTxtToDb(ConvertTxtToDb_Req in0){
	std::string in;
	{
		{
			uint32_t tmp12 = in0.TxtFileName.length();
			char tmp13[4];
			tmp13[0] = (uint32_t(tmp12) >> 24) & 0xFF;
			tmp13[1] = (uint32_t(tmp12) >> 16) & 0xFF;
			tmp13[2] = (uint32_t(tmp12) >> 8) & 0xFF;
			tmp13[3] = (uint32_t(tmp12) >> 0) & 0xFF;
			in.append(tmp13, 4);
			in.append(in0.TxtFileName);
		}
		{
			uint32_t tmp14 = in0.DbFileName.length();
			char tmp15[4];
			tmp15[0] = (uint32_t(tmp14) >> 24) & 0xFF;
			tmp15[1] = (uint32_t(tmp14) >> 16) & 0xFF;
			tmp15[2] = (uint32_t(tmp14) >> 8) & 0xFF;
			tmp15[3] = (uint32_t(tmp14) >> 0) & 0xFF;
			in.append(tmp15, 4);
			in.append(in0.DbFileName);
		}
		{
			uint32_t tmp16 = in0.RegionCsvFileName.length();
			char tmp17[4];
			tmp17[0] = (uint32_t(tmp16) >> 24) & 0xFF;
			tmp17[1] = (uint32_t(tmp16) >> 16) & 0xFF;
			tmp17[2] = (uint32_t(tmp16) >> 8) & 0xFF;
			tmp17[3] = (uint32_t(tmp16) >> 0) & 0xFF;
			in.append(tmp17, 4);
			in.append(in0.RegionCsvFileName);
		}
		in.append((char*)(&in0.Merge), 1);
	}
	char *out = NULL;
	int outLen = 0;
	Go2cppFn_ConvertTxtToDb((char *)in.data(), in.length(), &out, &outLen);
	std::string retValue;
	int outIdx = 0;
	{
		uint32_t tmp18 = 0;
		uint32_t tmp19 = uint32_t(uint8_t(out[outIdx+0]) << 24);
		uint32_t tmp20 = uint32_t(uint8_t(out[outIdx+1]) << 16);
		uint32_t tmp21 = uint32_t(uint8_t(out[outIdx+2]) << 8);
		uint32_t tmp22 = uint32_t(uint8_t(out[outIdx+3]) << 0);
		tmp18 = tmp19 | tmp20 | tmp21 | tmp22;
		outIdx+=4;
		retValue = std::string(out+outIdx, out+outIdx+tmp18);
		outIdx+=tmp18;
	}
	if (out != NULL) {
		free(out);
	}
	return retValue;
}

std::string TxtToXdb(TxtToXdbReq in0){
	std::string in;
	{
		{
			uint32_t tmp11 = in0.SrcFile.length();
			char tmp12[4];
			tmp12[0] = (uint32_t(tmp11) >> 24) & 0xFF;
			tmp12[1] = (uint32_t(tmp11) >> 16) & 0xFF;
			tmp12[2] = (uint32_t(tmp11) >> 8) & 0xFF;
			tmp12[3] = (uint32_t(tmp11) >> 0) & 0xFF;
			in.append(tmp12, 4);
			in.append(in0.SrcFile);
		}
		{
			uint32_t tmp13 = in0.DstFile.length();
			char tmp14[4];
			tmp14[0] = (uint32_t(tmp13) >> 24) & 0xFF;
			tmp14[1] = (uint32_t(tmp13) >> 16) & 0xFF;
			tmp14[2] = (uint32_t(tmp13) >> 8) & 0xFF;
			tmp14[3] = (uint32_t(tmp13) >> 0) & 0xFF;
			in.append(tmp14, 4);
			in.append(in0.DstFile);
		}
		{
			uint32_t tmp15 = in0.IndexPolicyS.length();
			char tmp16[4];
			tmp16[0] = (uint32_t(tmp15) >> 24) & 0xFF;
			tmp16[1] = (uint32_t(tmp15) >> 16) & 0xFF;
			tmp16[2] = (uint32_t(tmp15) >> 8) & 0xFF;
			tmp16[3] = (uint32_t(tmp15) >> 0) & 0xFF;
			in.append(tmp16, 4);
			in.append(in0.IndexPolicyS);
		}
	}
	char *out = NULL;
	int outLen = 0;
	Go2cppFn_TxtToXdb((char *)in.data(), in.length(), &out, &outLen);
	std::string retValue;
	int outIdx = 0;
	{
		uint32_t tmp17 = 0;
		uint32_t tmp18 = uint32_t(uint8_t(out[outIdx+0]) << 24);
		uint32_t tmp19 = uint32_t(uint8_t(out[outIdx+1]) << 16);
		uint32_t tmp20 = uint32_t(uint8_t(out[outIdx+2]) << 8);
		uint32_t tmp21 = uint32_t(uint8_t(out[outIdx+3]) << 0);
		tmp17 = tmp18 | tmp19 | tmp20 | tmp21;
		outIdx+=4;
		retValue = std::string(out+outIdx, out+outIdx+tmp17);
		outIdx+=tmp17;
	}
	if (out != NULL) {
		free(out);
	}
	return retValue;
}



// Qt:
#include <QMutexLocker>
#include <QtConcurrent/QtConcurrent>

RunOnUiThread::RunOnUiThread(QObject *parent) : QObject(parent), m_done(false)
{
    // 用signal里的Qt::QueuedConnection 将多线程里面的函数转化到ui线程里调用
    connect(this, SIGNAL(signal_newFn()), this, SLOT(slot_newFn()), Qt::QueuedConnection);
}

RunOnUiThread::~RunOnUiThread()
{
    {
        QMutexLocker lk(&this->m_Mutex);
        this->m_done = true;
        this->m_funcList.clear();
    }
    this->m_pool.clear();
    this->m_pool.waitForDone();
}

void RunOnUiThread::AddRunFnOn_OtherThread(std::function<void ()> fn)
{
    QMutexLocker lk(&this->m_Mutex);
    if (this->m_done) {
        return;
    }
    QtConcurrent::run(&this->m_pool, fn);
}

void RunOnUiThread::slot_newFn()
{
    QVector<std::function<void ()>> fn_vector;
    {
        QMutexLocker lk(&this->m_Mutex);
        if (this->m_funcList.empty() || this->m_done) {
            return;
        }
        fn_vector.swap(this->m_funcList);
    }

    for(std::function<void ()>& fn : fn_vector)
    {
        bool v_done = false;
        {
            QMutexLocker lk(&this->m_Mutex);
            v_done = this->m_done;
        }
        if (v_done) { // 快速结束
            return;
        }
        fn();
    }
}

void RunOnUiThread::AddRunFnOn_UiThread(std::function<void ()> fn)
{
    {
        QMutexLocker lk(&this->m_Mutex);
        if (this->m_done) {
            return;
        }
        m_funcList.push_back(fn);
    }
    emit this->signal_newFn();
}

bool RunOnUiThread::Get_Done()
{
	QMutexLocker lk(&this->m_Mutex);
	return this->m_done;
}

#include <QTimer>
#include <QLabel>
#include <QWidget>
#include <QPropertyAnimation>
#include <QPainter>
#include <QScreen>
#include <QHBoxLayout>
#include <QDesktopWidget>
#include <QApplication>

QString StringToRGBA(const QString &color);

Toast::Toast(QObject *parent) : QObject(parent)
{
    m_myWidget = new QWidget;
    m_myWidget->setFixedHeight(60);
    m_label = new QLabel;
    m_label->setFixedHeight(30);
    m_label->move(0,0);
    QFont ft;
    ft.setPointSize(10);
    m_label->setFont(ft);
    m_label->setAlignment(Qt::AlignCenter);
    m_label->setStyleSheet("color:white");
    m_myWidget->setStyleSheet("border: none;background-color:black;border-radius:10px");
    QHBoxLayout * la = new QHBoxLayout;
    la->addWidget(m_label);
    la->setContentsMargins(0,0,0,0);
    m_myWidget->setLayout(la);
    m_myWidget->hide();
    m_myWidget->setWindowFlags(Qt::FramelessWindowHint | Qt::Tool | Qt::WindowStaysOnTopHint);
    m_myWidget->setAttribute(Qt::WA_TranslucentBackground,true);
    m_timer = new QTimer();
    m_timer->setInterval(3000);
    connect(m_timer,SIGNAL(timeout()),this,SLOT(onTimerStayOut()));
}

Toast *Toast::Instance()
{
    static Toast instance;
    return &instance;
}

void Toast::setText(const QString &color,const QString &bgcolor,const int & mestime,const QString &text){
    QApplication::beep();
    QFontMetrics fm(m_label->font());
    int width = fm.boundingRect(text).width() + 30;
    m_myWidget->setFixedWidth(width);
    m_label->setFixedWidth(width);
    m_label->setText(text);
    QString style = QString("color:").append(StringToRGBA(color));
    m_label->setStyleSheet(style);

    m_myWidget->setStyleSheet(QString("border: none;border-radius:10px;")
                            .append("background-color:").append(StringToRGBA(bgcolor)));

    QDesktopWidget *pDesk = QApplication::desktop();
    m_myWidget->move((pDesk->width() - m_myWidget->width()) / 2, (pDesk->height() - m_myWidget->height()) / 2);
    m_myWidget->show();
    m_timer->setInterval(mestime);
    m_timer->stop();
    m_timer->start();
}

void Toast::SetError(const QString &text,const int & mestime){
     setText("FFFFFF","FF0000",mestime,text);
}

void Toast::SetSuccess(const QString &text,const int & mestime){
     setText("000000","00FF00",mestime,text);
}

void Toast::SetWaring(const QString &text,const int & mestime){
     setText("FF0000","FFFF00",mestime,text);
}

void Toast::SetTips(const QString &text,const int & mestime){
     setText("FFFFFF","0080FF",mestime,text);
}

QString StringToRGBA(const QString &color){
    int r = color.mid(0,2).toInt(nullptr,16);
    int g = color.mid(2,2).toInt(nullptr,16);
    int b = color.mid(4,2).toInt(nullptr,16);
    int a = color.length()>=8?color.mid(6,2).toInt(nullptr,16):QString("FF").toInt(nullptr,16);
    QString style = QString("rgba(").append(QString::number(r)).append(",")
            .append(QString::number(g)).append(",")
            .append(QString::number(b)).append(",")
            .append(QString::number(a))
            .append(");");
    return style;
}

void Toast::onTimerStayOut()
{
    m_timer->stop();
    m_myWidget->hide();
}
